version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/payments_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo
      - rabbitmq
      - prometheus
      - grafana

  mongo:
    image: mongo:6.0
    container_name: mongodb_docker
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: payments_db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_docker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  prometheus:
    image: prom/prometheus
    container_name: prometheus_docker
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana_docker
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  mongo_data:
  grafana_data:
