server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      host: localhost
      port: 27017
      database: payments_db

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true


logging:
  level:
    root: INFO
    com.example.payment: DEBUG
